apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ERXlOekl4TlRJek9Wb1hEVE15TURFeU5qSXhOVEl6T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUFBMClZWSGs2QTAwWVJYK05INUEzRXIyNS9YaG1HbVFDOUxSWEpWQzl1aXEvSXpmL3k1V3l1QTlKSncyNE43ZVhkTmsKWC93R0ZpZ0JyQWVmRXFDSHN5dC9OamRWYkhNOU9DUkhIWElLZDZLUTVCa3JRUWFVWHhzZkpUVnZFOEx2T25CLwo3OGN2bjQwR3praG0vMnZtQzQ4cFdmVkY2SitXRlF5aFhRR0E3ZlJ2d0JhRGpPVjdDNitEdnNzUVA0ZndWSU51ClIzanhzTWx2cXlUZUdpUkJQd3E2RnJIdzJweUFQbEhPdk9iRFAzb205VFI1d1NXbHFKVVRsS2xkQU83MVo1bkEKcnpvU2w1cHcrQkVOdEY1eXNEbWhpbzFHOCtHU3gwRk9UZzNSczdjSHZmRG4xZVhpWGpYaUI2MmRUbGdQU2ZYSAp0ZTY4S1lKb0FRZTZja3RSM2tNQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRV21UU2tCQ1FnSkxXT1Nxa000OERCVTN5Z3VUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFBZ1V1WTdaTgpLZFNRT29sam03cHJlL2EzQ0lGNlJOWjRaTjRUeFZHajZMRUs1am9jWFdWeTBrcWFDZUtJMHJ3RFRKTFVjY2owCi9CV0RjdEsxNDRvcDkrZ3ozK25IYm5kdS8xV2I4NWFFbGJvb2E2RkxMV09hMVJFanlKZ1R3ZkRGOGFmY2ZGV3oKMHBEaWp2eHRXMzlxK2w0aWxHNTVZTkx3YjQ0dTJ5MXFkWHEwaWZrQVlpckNpUElySlZwRlgrdEExK3RicUQ3awovRnFMVklFYUdsOGhhL1l3VnBPdStTVER2MGN3Z0Y0dGdUNVQ5WnA0dmhSQTc3M3l5WGFBdE14bExlVXQ1RU1WCjVsN2E3R2xIRUZKNWZINzg4NFdYd0dsL3c1Q0t1aVdWUE9IS3BoaFR2djlPTTRuWVpTVmdvQnhQTGo1elBQYzQKWC84SlV6ZGY4d3MyWXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltOXVNVGhLTW5nM1JFczJjVVp5ZFdWc2NGTlVkVkJNVW1oclZVUlZla3BCVERRMFRYQmtRamhqVmswaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMXVabTQ0Y2lJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pT0dWalptWTFaall0WTJSaE15MDBNVEV3TFdKbFpEa3RaVFV6WkRBMFpEVTRPVGszSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5zeWhxVTFOWUhONjNyc3RTanNNYVJNcG5FWU9JdXhMa0N0ZTFpa0xZNUU1RWxHUW5TVXpDQTJIR3R5endHcl9uSmtnUmpDZVM0eU9HRzNuOG1ZRVdsSE0zWkhSaUlfUzVoMEVwQjY3LWNyVTdQODk5OEZZUGE2V3lPM29mRHJmZno3SFd0dktDMExoOU5sdm0wc0llZTktQ3J4cnloNEdjQ21yM29ZQ2sweXR3RTdTdmlybjA2M2RUWE1BU1p4WE5SUXVEYU1leVUtSUU5bUlXWFZPX0xhY2hEVU0tWWRiandqMVZfVTVOQVhhdjAwMjB5NE9mN0g4czJzZmJSSmtWY0c3eENGNUdoZ0FPay02SjFQZXRvVVBIai1WQ1JzTDl2TDBOeThYQjJIOVVneHN4aE1yU25WNjhtWEEwQVJ6QWhVOHJoWGNHLW5VU1BKUU5CUVI1T0E=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 8ecff5f6-cda3-4110-bed9-e53d04d58997
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T15:09:57Z"
  name: default-token-nfn8r
  namespace: guestbook
type: kubernetes.io/service-account-token
